"""feat: add items table

Revision ID: 819d880e09d6
Revises: 57d192d3d72e
Create Date: 2025-08-17 22:24:44.687411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819d880e09d6'
down_revision: Union[str, None] = '57d192d3d72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'created_at')
    op.drop_column('items', 'id')
    # ### end Alembic commands ###
